name: login_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  pie_chart: ^5.0.1
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  web_socket_channel: ^3.0.0
  shared_preferences: ^2.0.8
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.0.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - icon.ico

flutter_icons:
  android: true
  ios: true
  image_path: "icon.ico"
